# Created by Crt Vavros, copyright Â© 2022 ZeroPass. All rights reserved.
name: dmrtd
description: Dart implementation of ICAO Doc 9303 MRTD, created by ZeroPass

version: 2.0.0

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  archive: ^4.0.7
  collection: ^1.19.1
  convert: ^3.1.2
  crypto: ^3.0.6
  fixnum: '>=1.0.0 <=1.1.1'
  flutter_nfc_kit: ^3.5.2
  logging: ^1.3.0
  meta: ^1.15.0
  tripledes_nullsafety: ^1.0.3
  pointycastle: ^3.9.1
  diffie_hellman: ^0.1.2
  crypto_keys_plus: ^0.4.0

dev_dependencies:
  flutter:      # needed for flutter_nfc_kit
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test: # needed for flutter_nfc_kit
    sdk: flutter
  lints: ^2.0.0
  test: 1.25.15